// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateItemInput struct {
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
}

type CreateOrderInput struct {
	Items      []*CreateOrderItemInput `json:"items"`
	InvoiceURL *string                 `json:"invoiceURL,omitempty"`
}

type CreateOrderItemInput struct {
	Name     string `json:"name"`
	Quantity int    `json:"quantity"`
}

type CreateSchoolInput struct {
	Name        string  `json:"name"`
	Address     *string `json:"address,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type CreateUserReturnType struct {
	Me    *User   `json:"me,omitempty"`
	Token *string `json:"token,omitempty"`
}

type Item struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	RawName   string     `json:"rawName"`
	Quantity  int        `json:"quantity"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type Items struct {
	Nodes    []*Item   `json:"nodes"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type Mutation struct {
}

type Order struct {
	ID         string       `json:"id"`
	OrderItems []*OrderItem `json:"orderItems"`
	InvoiceURL *string      `json:"invoiceURL,omitempty"`
	CreatedAt  time.Time    `json:"createdAt"`
	UpdatedAt  time.Time    `json:"updatedAt"`
	DeletedAt  *time.Time   `json:"deletedAt,omitempty"`
}

type OrderItem struct {
	ID        string     `json:"id"`
	Quantity  int        `json:"quantity"`
	Item      *Item      `json:"item"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type PageInfo struct {
	HasNextPage bool `json:"hasNextPage"`
}

type Query struct {
}

type School struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Address     *string    `json:"address,omitempty"`
	PhoneNumber *string    `json:"phoneNumber,omitempty"`
	Orders      []*Order   `json:"orders"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
}

type SchoolItem struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Quantity  int        `json:"quantity"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type SchoolOrder struct {
	ID          string             `json:"id"`
	School      *School            `json:"school,omitempty"`
	Items       []*SchoolOrderItem `json:"items"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
	DeliveredAt *time.Time         `json:"deliveredAt,omitempty"`
	DeletedAt   *time.Time         `json:"deletedAt,omitempty"`
}

type SchoolOrderItem struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Quantity  int        `json:"quantity"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type Schools struct {
	Nodes    []*School `json:"nodes"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type User struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}
