name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build
        run: go build -v ./cmd/main.go

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: secred_test
      DB_URL: postgresql://root:root@localhost:5432/secred_test?sslmode=disable
      DB_SSL_MODE: enable
      DOCKER: true

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: secred_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Run tests
        run: go test -v ./...
